camera:
  serial: '16906'
  exposure_time: 0.040661344537815114
  roi:
  - 100
  - 1440
  - 4
  - 1080
  - 1
  - 1
spectrometer:
  integration_time_us: 8920
references:
  dark_reference: data/dark_reference.npy
  bright_reference: data/bright_reference.npy
acquisition:
  measurements: 5
  interval_seconds: 1
storage:
  h5_file: data/acquisition.h5
calibration:
  target_detector_fraction: 0.85
  detector_max_counts: 65535
paths:
  calibration_folder: data/calibration
development:
  mode: simulation
calibration_results:
  camera:
    status: PASS
    mean_brightness: 48.12629776000976
    max_pixel: 225.0
    saturation_fraction: 0.0
  spectrometer:
    status: PASS
    peak_counts: 53894.500080354024
    detector_usage: 82.2377356837629
