experiment:
  sample_id: TMPTMA_CQ_TEST2lowint
  output_root: data
development:
  mode: simulation
acquisition:
  measurement_duration: 2700
  interval_seconds: 10
storage:
  image_mode: greyscale_when_color
  compression:
    method: gzip
    level: 4
spectrometer:
  integration_time_us: 10025
  target_detector_fraction: 0.95
  detector_max_counts: 65535
camera:
  serial: '16906'
  exposure_time: 0.028056890814295778
  roi:
  - 100
  - 1440
  - 4
  - 1080
  - 1
  - 1
calibration_results:
  camera:
    status: PASS
    mean_brightness: 34.79690704345703
    max_pixel: 202.0
    saturation_fraction: 0.0
  spectrometer:
    status: WARNING
    peak_counts: 60466.302136126025
    detector_usage: 92.26566283074087
