name: lwel-control-env

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11

  - numpy
  - scipy
  - pandas

  - matplotlib
  - pathlib

  - h5py

  - pillow

  - notebook
  - jupyterlab
  - ipykernel

  - pip

  - pip:
      - seabreeze
      - pylablib
      - keyboard